version: "3.8"
services:
  devops-java-springboot-color:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: devops-java-springboot-color
    restart: always
    environment:
      - MY_APP_COLOR=red
      - MY_SECRET_VALUE="very secret 1"
    ports:
      - "8080:8080"
