microservice-chart:
  namespace: 'payments'

  image:
    repository: 'iopcommonacr.azurecr.io/io-pagopa-payment-updater-ms'
    tag: 'latest'
    pullPolicy: Always

  livenessProbe:
    httpGet:
      path: '/api/v1/health/live'
      port: 9090
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: '/api/v1/health/ready'
      port: 9090
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  service:
    create: true
    port: 9090

  ingress:
    create: true
    host: 'weuprod02.payments.internal.io.pagopa.it'
    path: '/payment-updater/(.*)'

  resources:
    requests:
      memory: '96Mi'
      cpu: '50m'
    limits:
      memory: '256Mi'
      cpu: '200m'

  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: '60'

  envConfig:
    # required
    NODE_ENV: 'production'
    WEBSITE_NODE_DEFAULT_VERSION: '14.16.0'
    WEBSITE_SITE_NAME: 'io-p-weuprod02-functions-service-payments' # required to show cloud role name in application insights
    # app specific
    BOOTSTRAP_SERVER_MESSAGE: 'io-space-hub-pu-messages.servicebus.windows.net:9093'
    BOOTSTRAP_SERVER_PAYMENT: 'io-space-hub-pu-messages.servicebus.windows.net:9093'
    BOOTSTRAP_SERVER_PAYMENTUPDATES: 'io-space-hub-pu-messages.servicebus.windows.net:9093'
    CHECKPOINT_SIZE: '10'
    KAFKA_MESSAGE: 'message'
    KAFKA_PAYMENT_UPDATES: 'payment-updates'
    KAFKA_PAYMENTS: 'payments'
    MESSAGE_STATUS_ENDPOINT: 'https://io-d-mock-app-backend.azurewebsites.net/api/v1/messages/{fiscalcode}/{id}/messages-status'
    MONGO_DATABASE: 'io-d-producer-mongodb'
    PROXY_ENDPOINT: 'https://io-d-mock-app-backend.azurewebsites.net/api/v1/payment-requests/'
    RESTCALL_INTERVAL_FUNCTION: '10000'
    RESTCALL_MAX_ATTEMPTS: '3'
    SASL_MECHANISM_PAYMENT: 'PLAIN'
    SECURITY_PROTOCOL_PAYMENT: 'SASL_SSL'

  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'appinsights-instrumentationkey'
    # app specific
    KAFKA_URL_MESSAGE: 'KAFKA-URL-MESSAGE-beta'
    KAFKA_URL_PAYMENT: 'KAFKA-URL-PAYMENT-beta'
    KAFKA_URL_PAYMENTUPDATES: 'KAFKA-URL-PAYMENTUPDATES-beta'
    MONGO_DATABASE_URI: 'MONGO-DATABASE-URI-beta'

  keyvault:
    name: 'io-p-payments-kv'
    tenantId: '7788edaf-0346-4068-9d79-c868aed15b3d'
