microservice-chart:
  namespace: "payments"
  image:
    repository: "iopcommonacr.azurecr.io/devops-test-cicd-k8s"
    tag: "1.1.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: "/status/live"
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: "/status/ready"
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    port: 8080
  ingress:
    create: true
    host: "weuprod01.payments.internal.io.pagopa.it"
    path: "/api/v1/devops/(.*)"
    # path: '/(api/v1/payment/.*)'
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "70"
  envConfig:
    # required
    WEBSITE_SITE_NAME: "io-p-weuprod01-devops-test-cicd-k8s" # required to show cloud role name in application insights
    # app specific
    MY_APP_COLOR: "red"

  keyvault:
    name: "io-p-payments-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
